-- Phase 13: Migrate Case Study Content to content_registry.metadata.caseStudy
-- Idempotent content migration script

UPDATE content_registry
SET metadata = '{"tags":["Product Design","UX/UI","AI"],"badge":"01","kicker":"PRODUCT - QR - LOST & FOUND","subtitle":"A QR-powered recovery experience designed around one principle: the finder should not have to become a user.","caseStudy":{"version":1,"type":"custom","title":"WINNI","subtitle":"Giving lost things a way back.","customComponent":"WinniCaseStudy"},"description":"A QR-powered recovery experience designed around one principle: the finder should not have to become a user."}'::jsonb,
    updated_at = NOW()
WHERE slug = 'winni';

UPDATE content_registry
SET metadata = '{"tags":["Product Design","AI","RAG"],"year":2025,"badge":"02","kicker":"PRODUCT - OPERATIONAL INTELLIGENCE","subtitle":"Designing an operational layer that connects estimation, delivery, margins, cash flow and AI-assisted decisions.","caseStudy":{"version":1,"type":"custom","title":"Assestini","subtitle":"Operational Intelligence Platform","customComponent":"AssestiniCaseStudy"},"description":"Designing an operational layer that connects estimation, delivery, margins, cash flow and AI-assisted decisions."}'::jsonb,
    updated_at = NOW()
WHERE slug = 'assestini';

UPDATE content_registry
SET metadata = '{"tags":["Front-End","Bootstrap","Figma"],"badge":"03","kicker":"WEB · FIGMA → CODE","subtitle":"Translating a Figma interface into responsive HTML, CSS, Bootstrap and JavaScript for a community platform.","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"WEB DESIGN → FRONT-END INTEGRATION","title":"Cha9a9a","lead":"Turning a Figma interface into a responsive HTML/CSS/Bootstrap/JavaScript experience for a community platform.","metaChips":["Cha9a9a.tn / web under construction","UI Developer · Front-End Integrator"],"image":"cha9a9a-homepage-reference.png","imageAlt":"Cha9a9a homepage reference screenshot supplied by Naïm","caption":"Selected project evidence."},"challenge":{"eyebrow":"THE CHALLENGE","title":"Translate a visual concept into a responsive, usable web experience.","copy":"Cha9a9a is a community-oriented platform concept. My role focused on taking the approved Figma direction and translating it into a responsive front-end experience while preserving the visual hierarchy, cards, calls to action and content rhythm.","role":"UI Developer · Front-End Integrator","context":"Cha9a9a.tn · website currently under construction"},"contribution":{"eyebrow":"MY CONTRIBUTION","title":"From Figma handoff to implementation.","items":["Integrated the approved Figma mockups into semantic HTML.","Built responsive layouts with CSS and Bootstrap.","Implemented interactive behaviors with JavaScript.","Translated cards, navigation, hero sections, categories and FAQ patterns into reusable UI structures.","Focused on visual fidelity between design and browser output.","Prepared the implementation so content and imagery can evolve without rebuilding the interface."],"process":[{"step":"01","title":"Read","desc":"Understand the Figma structure, components, spacing and hierarchy."},{"step":"02","title":"Translate","desc":"Convert visual decisions into semantic HTML and Bootstrap layout."},{"step":"03","title":"Refine","desc":"Tune CSS, typography, spacing and responsive behavior."},{"step":"04","title":"Validate","desc":"Compare browser output with the intended design and iterate."}]},"evidence":{"eyebrow":"DESIGN → CODE","title":"A snapshot of the interface I translated into front-end.","image":"cha9a9a-homepage-reference.png","imageAlt":"Cha9a9a.tn homepage screenshot showing the Figma-to-HTML implementation target","caption":"Cha9a9a.tn — provided homepage reference showing the visual system, content structure and responsive UI target."},"technology":{"eyebrow":"TECHNOLOGY","title":"Tools and technologies","tags":["Figma","HTML","CSS","Bootstrap","JavaScript","Responsive UI"]}},"description":"Translating a Figma interface into responsive HTML, CSS, Bootstrap and JavaScript for a community platform."}'::jsonb,
    updated_at = NOW()
WHERE slug = 'cha9a9a';

UPDATE content_registry
SET metadata = '{"tags":["n8n","OpenAI","RAG"],"badge":"04","kicker":"AI AGENT","logoMark":{"letter":"NC","className":"copilot"},"subtitle":"AI Agent · n8n · Memory · Actions","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"AI SYSTEM · N8N · PERSONAL OPERATING LAYER","title":"Naïm Copilot","lead":"A personal AI agent that connects memory, knowledge, projects and actions so work can be queried and updated through a single conversational interface.","metaChips":["Personal AI system","AI Product Designer · AI Builder · Automation Architect"],"image":"cover-copilot-naim.png","imageAlt":"Naïm Copilot n8n workflow screenshot showing Telegram, AI Agent, memory and project tools","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can one assistant understand my professional context, remember decisions, search projects and trigger actions instead of behaving like a generic chatbot?","role":"AI Product Designer · AI Builder · Automation Architect","context":"Personal AI system"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Designed the conversational operating model around memory, knowledge and project state.","Built an n8n workflow for Telegram text and voice input.","Connected PostgreSQL chat memory and structured knowledge.","Added project search, project update, decision context and action planning tools."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"The-work-behind-the-interface.png","imageAlt":"Naïm Copilot n8n workflow screenshot showing Telegram, AI Agent, memory and project tools","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["n8n","Google Gemini","PostgreSQL","Telegram","AI Agents","RAG","MCP","Automation"]}},"description":"AI Agent · n8n · Memory · Actions"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'naim-copilot';

UPDATE content_registry
SET metadata = '{"tags":["n8n","Gemini","Telegram"],"badge":"05","kicker":"AI AUTOMATION","subtitle":"Daily Job Search · AI scoring","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"AI AUTOMATION · JOB SEARCH · SCORING","title":"Career OS · Daily Job Search","lead":"An automated career-search workflow that collects opportunities, removes duplicates, scores fit and sends a focused daily digest.","metaChips":["Personal automation system","Product Designer · AI Workflow Builder"],"image":"daily-jobsearch-os-cover.png","imageAlt":"Career OS n8n workflow screenshot showing job sources, deduplication, AI fit scoring and digest","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can repetitive job searching become a consistent pipeline where relevant roles are collected, evaluated and prioritized automatically?","role":"Product Designer · AI Workflow Builder","context":"Personal automation system"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Combined multiple remote job sources.","Flattened and deduplicated results to keep only new URLs.","Used an AI scoring step to assess fit against the career profile.","Saved results to a pipeline and delivered email / Telegram digests."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"daily-jobsearch-os-cover.png","imageAlt":"Career OS n8n workflow screenshot showing job sources, deduplication, AI fit scoring and digest","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["n8n","Google Gemini","Job APIs","PostgreSQL","AI scoring","Email","Telegram"]}},"description":"Daily Job Search · AI scoring"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'career-os';

UPDATE content_registry
SET metadata = '{"tags":["OutSystems","Figma"],"badge":"06","kicker":"DIGITAL SERVICES","subtitle":"Digital services · UX/UI · OutSystems","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"SAUDI ARABIA · GOVERNMENT SECTOR","title":"Saudi · Government Digital Services","lead":"UX/UI and low-code product work delivered through ENVNT / Wevioo for Saudi digital environments. Client project names are intentionally omitted from the public portfolio.","metaChips":["ENVNT / Wevioo · Saudi Arabia","Senior UX/UI Designer · UI Developer"],"image":"dga_government_services_case_hero_skeleton.png","imageAlt":"approved Saudi government digital service interface screenshot, with confidential project names removed","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can complex government requirements and workflows become clear, consistent and production-ready digital interfaces?","role":"Senior UX/UI Designer · UI Developer","context":"ENVNT / Wevioo · Saudi Arabia"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Translated requirements and workflows into usable interfaces.","Designed responsive screens and reusable UI patterns.","Collaborated with business and development teams.","Implemented UI in OutSystems where required."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"dga_government_services_case_evidence_skeleton.png","imageAlt":"approved Saudi government digital service interface screenshot, with confidential project names removed","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["Figma","UX/UI","OutSystems","Design Systems","Responsive UI"]}},"description":"Digital services · UX/UI · OutSystems"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'saudi-government';

UPDATE content_registry
SET metadata = '{"tags":["Mendix","Figma"],"badge":"07","kicker":"FINANCIAL SERVICES","subtitle":"Financial services · UX/UI · Mendix","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"SAUDI ARABIA · BANKING SECTOR","title":"Saudi · Banking & Financial Services","lead":"UX/UI and Mendix interface work in a Saudi banking environment through ENVNT / Wevioo. Confidential client and project names are intentionally omitted.","metaChips":["ENVNT / Wevioo · Saudi Arabia","UX Designer · Mendix UI Developer"],"image":"dga_antifraud_case_hero_skeleton_v2.png","imageAlt":"approved Saudi banking interface skeleton","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can business requirements, use cases and workflows be translated into a clear banking interface that can be implemented in a low-code environment?","role":"UX Designer · Mendix UI Developer","context":"ENVNT / Wevioo · Saudi Arabia"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Translated SRS, use cases and workflows into Figma interfaces.","Worked with BA and development teams to clarify the experience.","Implemented UI components and screens in Mendix.","Worked within the context of regulated financial services."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"dga_antifraud_case_evidence_skeleton_v2.png","imageAlt":"approved Saudi banking interface evidence skeleton","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["Figma","Mendix","UX/UI","SRS","Low-Code","Design Systems"]}},"description":"Financial services · UX/UI · Mendix"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'saudi-banking';

UPDATE content_registry
SET metadata = '{"tags":["OutSystems","Figma"],"badge":"08","kicker":"GOVERNMENT DESIGN SYSTEM","subtitle":"Government design system · UI · OutSystems","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"SAUDI ARABIA · DIGITAL GOVERNMENT","title":"DGA · Digital Government Experience","lead":"A focused look at my contribution to digital government UX/UI and design-system work in Saudi Arabia.","metaChips":["ENVNT / Wevioo · Saudi Arabia","UX/UI Designer · Design System Contributor · OutSystems UI"],"image":"dga_digital_government_case_hero_skeleton.png","imageAlt":"approved Saudi government digital service interface screenshot, with confidential project names removed","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can government interfaces remain consistent, accessible and implementation-ready across digital services?","role":"UX/UI Designer · Design System Contributor · OutSystems UI","context":"ENVNT / Wevioo · Saudi Arabia"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Worked on UX/UI for digital government services.","Contributed to reusable design-system patterns.","Translated visual design into OutSystems UI.","Collaborated with delivery teams across design and development."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"dga_digital_government_case_evidence_skeleton.png","imageAlt":"approved DGA-related interface or design-system screenshot, with confidential project details removed","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["Figma","Design Systems","OutSystems","UX/UI","Government Digital Services"]}},"description":"Government design system · UI · OutSystems"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'dga';

UPDATE content_registry
SET metadata = '{"tags":["OutSystems","Figma"],"badge":"09","kicker":"REGULATED DIGITAL SERVICES","subtitle":"Regulated digital services · UX/UI · OutSystems","caseStudy":{"version":1,"type":"standard","hero":{"eyebrow":"SAUDI ARABIA · REGULATORY / HEALTHCARE","title":"Saudi · Regulatory / Healthcare Digital Services","lead":"UX/UI and OutSystems interface work for regulated digital services through ENVNT / Wevioo, presented publicly by sector rather than client project name.","metaChips":["ENVNT / Wevioo · Saudi Arabia","UX/UI Designer · OutSystems UI"],"image":"dga_regulatory_healthcare_case_hero_skeleton.png","imageAlt":"approved Saudi regulatory or healthcare service interface screenshot, anonymized for public portfolio","caption":null},"challenge":{"eyebrow":"THE CHALLENGE","title":"A clear problem deserves a clear product response.","copy":"How can regulated service workflows be made easier to understand and use while staying consistent with an existing digital platform?","role":"UX/UI Designer · OutSystems UI","context":"ENVNT / Wevioo · Saudi Arabia"},"contribution":{"eyebrow":"WHAT I DID","title":"From ambiguity to a usable system.","items":["Designed and refined service interfaces.","Worked within existing product and design constraints.","Created responsive UI patterns for low-code implementation.","Collaborated with delivery teams to iterate on the experience."],"process":[{"step":"01","title":"Frame","desc":"Clarify the problem, users and constraints."},{"step":"02","title":"Structure","desc":"Turn requirements into flows and product logic."},{"step":"03","title":"Design","desc":"Create clear, reusable and implementation-ready UI."},{"step":"04","title":"Build","desc":"Connect the design to technology and iterate."}]},"evidence":{"eyebrow":"SELECTED EVIDENCE","title":"The work behind the interface.","image":"dga_regulatory_healthcare_case_evidence_skeleton.png","imageAlt":"approved Saudi regulatory or healthcare service interface screenshot, anonymized for public portfolio","caption":null},"technology":{"eyebrow":"TECHNOLOGY","title":"Technology","tags":["Figma","OutSystems","UX/UI","Responsive Design","Design Systems"]}},"description":"Regulated digital services · UX/UI · OutSystems"}'::jsonb,
    updated_at = NOW()
WHERE slug = 'saudi-regulatory';
